import { ACTION_DECISIONS, EvidenceKind, FinalReview, Finding, PRACTICAL_CHECKS, PracticalResult, QUALITY_INDICATORS, QualityDomain, QualityRating, QuickFinding, READINESS_DECISIONS } from "./evidence-model";

type Scenario = { practical?: Record<string, PracticalResult>; quality?: Record<string, QualityRating>; qualityDefault?: QualityRating; possibleBlocker?: FinalReview["possibleBlocker"]; keep: string; priority: string; best: string; use: string; blocker?: string; support?: string };
type ReviewerProfile = { testerId: string; device: string; internet: string; hrba: Scenario; pm: Scenario };

const practical = (overrides: Record<string, PracticalResult> = {}) => PRACTICAL_CHECKS.map(([xmlName, , coverage]) => ({
  xmlName, result: overrides[xmlName] ?? (coverage === "assigned" ? "NOT TESTED" : "PASS"), applicable: coverage === "core" || xmlName in overrides,
  what: overrides[xmlName] && overrides[xmlName] !== "PASS" ? `The simulated reviewer recorded ${overrides[xmlName].toLowerCase()} for this check.` : undefined,
  recommendation: overrides[xmlName] && overrides[xmlName] !== "PASS" ? "Review the evidence, make the smallest correction, and recheck the learner journey." : undefined,
}));

const quality = (course: "hrba" | "pm", defaultRating: QualityRating, overrides: Record<string, QualityRating> = {}) => QUALITY_INDICATORS
  .filter((indicator) => indicator.appliesTo === "all" || indicator.appliesTo === course)
  .map((indicator) => { const rating = overrides[indicator.xmlName] ?? defaultRating; return { xmlName: indicator.xmlName, rating, comment: rating === "0 BLOCKED" || rating === "1 FRAGILE" ? "The evidence shows a specific learner difficulty that should be corrected and retested." : undefined }; });

function review(profile: ReviewerProfile, course: "hrba" | "pm", index: number): FinalReview {
  const scenario = profile[course]; const id = `SIM-R-${course.toUpperCase()}-${String(index + 1).padStart(2, "0")}`;
  const evidence: [EvidenceKind, QualityDomain | "Cross-cutting", string, string][] = [["KEEP", "Cross-cutting", "j_keep", scenario.keep], ["Priority Improvement", "Cross-cutting", "j_priority_improvement", scenario.priority], ["Best Decision Activity", "Learning & Better Decisions", "e_best_decision_activity", scenario.best], ["Workplace Use", "Application & Transfer", "g_practical_example", scenario.use]];
  if (scenario.blocker) evidence.push(["Possible Blocker", "Cross-cutting", "j_blocker_explain", scenario.blocker]);
  if (scenario.support) evidence.push(["Support Need", "DEC Operational Readiness", "g_support_needs", scenario.support]);
  const possibleBlocker = scenario.possibleBlocker ?? "no";
  return { id, sourceId: `SIM-${course === "hrba" ? "91" : "92"}${String(index + 1).padStart(2, "0")}`, sourceUuid: `synthetic-${course}-${String(index + 1).padStart(2, "0")}`, submittedAt: new Date(Date.UTC(2026, 7, 10 + index, course === "hrba" ? 8 : 13, 15)).toISOString(), testerId: profile.testerId, course, device: profile.device, internet: profile.internet, completion: index === 3 && course === "pm" ? "Most of the course" : "Whole course", practical: practical(scenario.practical), quality: quality(course, scenario.qualityDefault ?? "2 WORKABLE", scenario.quality), qualitative: evidence.map(([kind, domain, sourceField, excerpt], evidenceIndex) => ({ id: `${id}-E${evidenceIndex + 1}`, reviewId: id, testerId: profile.testerId, course, kind, domain, sourceField, excerpt })), possibleBlocker, actionRecommendation: possibleBlocker === "yes" ? ACTION_DECISIONS[0] : possibleBlocker === "not_sure" ? ACTION_DECISIONS[3] : ACTION_DECISIONS[1], readinessRecommendation: possibleBlocker === "yes" ? READINESS_DECISIONS[2] : possibleBlocker === "not_sure" ? READINESS_DECISIONS[3] : READINESS_DECISIONS[1] };
}

const profiles: ReviewerProfile[] = [
  { testerId: "SIM-T01", device: "Smartphone", internet: "Sometimes interrupted", hrba: { practical: { b01_account_activation: "PASS", b07_correct_progression: "PASS WITH ISSUE" }, quality: { d02_navigation: "1 FRAGILE", d07_mobile_learning: "1 FRAGILE", eh03_design: "3 STRONG", g02_tool_adapt: "3 STRONG" }, keep: "Retain the project-design repair activity because it turns analysis into a concrete programme choice.", priority: "Keep the next action visible on smaller screens and reduce excess vertical space.", best: "The design-repair activity showed how an exclusion finding should change an activity plan.", use: "A CSO could use the participation checklist before a community consultation.", support: "A one-page mobile navigation tip would help first-time Hub users." }, pm: { practical: { b16_second_device: "PASS" }, quality: { ep03_planning: "3 STRONG", ep05_monitor_adapt: "3 STRONG", f02_cases: "3 STRONG" }, keep: "Retain the continuing project case across planning, delivery, monitoring and closure.", priority: "Shorten two long instruction blocks on mobile without removing decision context.", best: "Sequencing deliverables, owners and budget assumptions made the trade-offs visible.", use: "The team could adapt the work-breakdown and responsibility tools at project inception." } },
  { testerId: "SIM-T02", device: "Laptop", internet: "Mostly reliable", hrba: { qualityDefault: "3 STRONG", quality: { d05_pacing: "2 WORKABLE", h04_common_difficulties: "2 WORKABLE" }, keep: "Corrective feedback explains why replacing a duty-bearer is a weak decision.", priority: "Add one short orientation cue showing where saved progress appears.", best: "The responsibility-boundary scenario made the consequence of a weak role choice clear.", use: "The actor and responsibility map could be used during project inception." }, pm: { qualityDefault: "3 STRONG", quality: { c03_find_continue: "2 WORKABLE", h03_feedback_route: "2 WORKABLE" }, keep: "Retain the progression from purpose to results, delivery and closure.", priority: "Make the route back to the learner dashboard more explicit after an assessment.", best: "The results-chain activity required a defensible choice rather than recall.", use: "The results chain can support proposal design and partner review." } },
  { testerId: "SIM-T03", device: "Smartphone", internet: "Frequently interrupted", hrba: { practical: { b10_media: "PASS WITH ISSUE", b13_return_completed: "PASS" }, quality: { d05_pacing: "1 FRAGILE", d07_mobile_learning: "1 FRAGILE", e03_feedback_decisions: "3 STRONG" }, keep: "Retain the corrective feedback in the power-analysis scenario.", priority: "Break the longest case screen into two purposeful steps for phones.", best: "The power mapping task helped identify whose voice was missing from a consultation.", use: "The power map could be reused before stakeholder engagement.", support: "Provide a low-bandwidth note where media is optional rather than required." }, pm: { practical: { b12_completion_certificate: "PASS WITH ISSUE" }, quality: { h02_records: "1 FRAGILE", ep06_closure: "3 STRONG" }, keep: "Retain the closure and handover decisions; they address a common project weakness.", priority: "Clarify the certificate download state after completion on a phone.", best: "The closure activity connected handover, accountability and learning.", use: "A project manager could adapt the closure checklist before partner handover." } },
  { testerId: "SIM-T04", device: "Laptop", internet: "Mostly reliable", hrba: { qualityDefault: "3 STRONG", quality: { f03_adaptability: "2 WORKABLE" }, keep: "Retain the distinction between rights-holders, duty-bearers and CSO responsibilities.", priority: "Add one smaller-CSO example alongside the consortium case.", best: "The role scenario prevented the CSO from substituting for a public duty-bearer.", use: "The role matrix could strengthen partnership discussions." }, pm: { practical: { b06_required_gating: "FAIL", b07_correct_progression: "FAIL", b11_final_assessment: "NOT TESTED", b12_completion_certificate: "NOT TESTED" }, quality: { d06_corrective_feedback: "0 BLOCKED", ep04_risk_change: "1 FRAGILE", e05_assessment_alignment: "NOT TESTED / N/A" }, possibleBlocker: "yes", keep: "Retain the realistic risk register and the continuing project case.", priority: "Correct the risk-activity answer mapping and retest progression through assessment and certificate.", best: "The risk-response activity would be valuable once the progression defect is corrected.", use: "The risk register could support monthly project reviews.", blocker: "The required risk activity remained locked after a response consistent with the instructions, preventing course completion." } },
  { testerId: "SIM-T05", device: "Tablet", internet: "Sometimes interrupted", hrba: { practical: { b04_course_separation: "PASS" }, quality: { f02_cases: "3 STRONG", f04_respectful_inclusion: "3 STRONG", h01_support: "1 FRAGILE" }, keep: "Retain the respectful treatment of exclusion and participation.", priority: "Place the support contact beside the first complex activity.", best: "The inclusion scenario required choosing who participates and how.", use: "The participation prompt could be adapted for community meeting design.", support: "Show the DEC support route at the point of difficulty, not only in the footer." }, pm: { quality: { ep02_roles: "3 STRONG", g03_decision_connection: "3 STRONG", h01_support: "1 FRAGILE" }, keep: "Retain the responsibility matrix and its link to delivery decisions.", priority: "Repeat the support contact near the first planning tool download.", best: "The stakeholder-responsibility activity exposed gaps in ownership.", use: "The responsibility matrix can be used at a kickoff meeting.", support: "A short worked example would help teams adapt the downloadable planning tool." } },
  { testerId: "SIM-T06", device: "Laptop", internet: "Mostly reliable", hrba: { quality: { e01_understanding: "3 STRONG", eh05_meal: "3 STRONG", g01_workplace_use: "3 STRONG" }, keep: "Retain the link between HRBA evidence, adaptation and accountability.", priority: "Give the MEAL indicator example a short plain-language introduction.", best: "The indicator activity distinguished participation counts from meaningful influence.", use: "The team could adapt the indicator test during MEAL plan review." }, pm: { quality: { ep04_risk_change: "1 FRAGILE", ep05_monitor_adapt: "3 STRONG" }, keep: "Retain the monitoring-to-adaptation decision sequence.", priority: "Clarify the difference between a risk, an issue and a change request.", best: "The monitoring activity required choosing whether evidence justified adaptation.", use: "The adaptation prompt could be used in quarterly reviews." } },
  { testerId: "SIM-T07", device: "Smartphone", internet: "Mostly reliable", hrba: { quality: { d04_readability: "3 STRONG", eh02_power_inclusion: "3 STRONG", d07_mobile_learning: "2 WORKABLE" }, keep: "Retain the concise power and inclusion prompts.", priority: "Keep downloadable tool labels visible after they are opened.", best: "The power scenario made informal influence visible.", use: "The prompts could be used in stakeholder analysis." }, pm: { practical: { b12_completion_certificate: "PASS WITH ISSUE", b14_cross_user: "PASS" }, quality: { h02_records: "1 FRAGILE", ep01_purpose_results: "3 STRONG" }, keep: "Retain the purpose-and-results diagnostic.", priority: "Make the completed-course certificate action clearer on small screens.", best: "The purpose activity exposed a weak result statement before planning began.", use: "The diagnostic could improve concept-note review." } },
  { testerId: "SIM-T08", device: "Laptop", internet: "Frequently interrupted", hrba: { practical: { b08_progress_persistence: "PASS WITH ISSUE" }, quality: { c05_leave_return: "1 FRAGILE", eh04_implementation: "3 STRONG" }, possibleBlocker: "not_sure", keep: "Retain the implementation decision scenarios.", priority: "Investigate one delayed progress update after reconnecting from an interrupted session.", best: "The implementation scenario balanced participation quality with delivery pressure.", use: "The decision prompt could support field-team reflection.", blocker: "Progress appeared one step behind immediately after reconnecting; a later refresh restored it, so recurrence needs checking." }, pm: { practical: { b08_progress_persistence: "PASS" }, quality: { c05_leave_return: "2 WORKABLE", ep03_planning: "3 STRONG" }, keep: "Retain the integrated plan connecting deliverables, time and resources.", priority: "Show a clearer saved-state confirmation after a long planning activity.", best: "The integrated plan revealed an unrealistic resource assumption.", use: "The planning canvas could support internal proposal review." } },
  { testerId: "SIM-T09", device: "Tablet", internet: "Mostly reliable", hrba: { practical: { b16_second_device: "NOT TESTED" }, quality: { f01_language: "3 STRONG", f03_adaptability: "3 STRONG", g02_tool_adapt: "3 STRONG" }, keep: "Retain the plain language and adaptable tools.", priority: "Explain which examples are illustrative rather than required templates.", best: "The design activity connected analysis to a practical programme adjustment.", use: "The checklist could support a proposal quality review." }, pm: { practical: { b16_second_device: "NOT TESTED" }, quality: { f01_language: "3 STRONG", ep06_closure: "3 STRONG" }, keep: "Retain the practical closure checklist.", priority: "Add one example from a small grant-funded project.", best: "The handover decision highlighted ownership after funding ends.", use: "The checklist could support project closure planning." } },
  { testerId: "SIM-T10", device: "Laptop", internet: "Reliable", hrba: { practical: { b13_return_completed: "PASS", b14_cross_user: "PASS" }, qualityDefault: "3 STRONG", quality: { h04_common_difficulties: "2 WORKABLE" }, keep: "Retain the coherent progression from principles to applied design and MEAL decisions.", priority: "Add a facilitator note for teams discussing difficult power dynamics.", best: "The final design task required combining role, power and inclusion evidence.", use: "The full sequence could structure an internal programme design review." }, pm: { practical: { b01_account_activation: "PASS", b04_course_separation: "PASS", b13_return_completed: "PASS", b14_cross_user: "PASS", b16_second_device: "PASS" }, qualityDefault: "3 STRONG", quality: { h04_common_difficulties: "2 WORKABLE" }, keep: "Retain the end-to-end project case and its decision checkpoints.", priority: "Add a short glossary for teams using different project terminology.", best: "The final adaptation decision connected monitoring evidence to delivery choices.", use: "The sequence could structure a project health review." } },
];

export const SAMPLE_REVIEWS: FinalReview[] = profiles.flatMap((profile, index) => [review(profile, "hrba", index), review(profile, "pm", index)]);

export const SAMPLE_QUICK_FINDINGS: QuickFinding[] = [
  { id: "SIM-Q-601", sourceId: "SIM-80601", submittedAt: "2026-08-10T07:40:00Z", testerId: "SIM-T01", course: "hrba", stableId: "HRBA M2 / mobile next action", whatHappened: "The Continue action appeared below excess whitespace on a phone.", recommendation: "Reduce the empty space and keep the next action visible." },
  { id: "SIM-Q-602", sourceId: "SIM-80602", submittedAt: "2026-08-12T09:10:00Z", testerId: "SIM-T03", course: "hrba", stableId: "HRBA M2 / mobile next action", whatHappened: "A second phone review found the same long gap before Continue.", recommendation: "Treat this as a repeated mobile usability finding." },
  { id: "SIM-Q-603", sourceId: "SIM-80603", submittedAt: "2026-08-11T11:20:00Z", testerId: "SIM-T02", course: "hrba", stableId: "HRBA M4 / corrective feedback", whatHappened: "Feedback clearly explained why the first response blurred the duty-bearer role.", recommendation: "Retain this feedback pattern." },
  { id: "SIM-Q-604", sourceId: "SIM-80604", submittedAt: "2026-08-14T13:05:00Z", testerId: "SIM-T04", course: "pm", stableId: "PM M4 / risk activity", whatHappened: "Progression remained locked after a response consistent with the instructions.", recommendation: "Check answer mapping and diagnostic feedback." },
  { id: "SIM-Q-605", sourceId: "SIM-80605", submittedAt: "2026-08-14T13:18:00Z", testerId: "SIM-T04", course: "pm", stableId: "PM M4 / risk activity retry", whatHappened: "The same activity remained locked after a careful retry, so assessment and certificate were not reached.", recommendation: "Correct and independently retest the full completion route." },
  { id: "SIM-Q-606", sourceId: "SIM-80606", submittedAt: "2026-08-13T15:00:00Z", testerId: "SIM-T03", course: "pm", stableId: "PM completion / phone", whatHappened: "Completion registered, but the certificate action was easy to miss on a phone.", recommendation: "Make the certificate state and action more prominent." },
  { id: "SIM-Q-607", sourceId: "SIM-80607", submittedAt: "2026-08-17T08:50:00Z", testerId: "SIM-T07", course: "pm", stableId: "PM completion / phone", whatHappened: "Another phone reviewer also paused before finding the certificate action.", recommendation: "Test the revised completion panel at common mobile widths." },
  { id: "SIM-Q-608", sourceId: "SIM-80608", submittedAt: "2026-08-15T10:30:00Z", testerId: "SIM-T05", course: "hub", stableId: "Support route / first complex activity", whatHappened: "The support contact was available in the footer but not beside the point of difficulty.", recommendation: "Repeat the support route contextually." },
  { id: "SIM-Q-609", sourceId: "SIM-80609", submittedAt: "2026-08-16T12:25:00Z", testerId: "SIM-T06", course: "pm", stableId: "PM M4 / risk terminology", whatHappened: "Risk, issue and change request were used close together and required rereading.", recommendation: "Add a compact comparison before the activity." },
  { id: "SIM-Q-610", sourceId: "SIM-80610", submittedAt: "2026-08-18T06:55:00Z", testerId: "SIM-T08", course: "hub", stableId: "Reconnect / progress", whatHappened: "Progress appeared one step behind immediately after reconnecting, then corrected after refresh.", recommendation: "Monitor recurrence under interrupted connectivity." },
  { id: "SIM-Q-611", sourceId: "SIM-80611", submittedAt: "2026-08-19T14:05:00Z", testerId: "SIM-T09", course: "hrba", stableId: "HRBA M3 / adaptable tool", whatHappened: "The participation checklist was easy to adapt without losing its decision purpose.", recommendation: "Retain the adaptable format." },
  { id: "SIM-Q-612", sourceId: "SIM-80612", submittedAt: "2026-08-20T09:35:00Z", testerId: "SIM-T10", course: "pm", stableId: "PM M6 / closure", whatHappened: "The closure checklist made handover ownership explicit.", recommendation: "Retain as designed." },
];

export const SAMPLE_FINDINGS: Finding[] = [
  { id: "SIM-F-001", course: "hub", domain: "Access & Entry", evidence: "An earlier simulated activation link expired; replacement-link handling was retested successfully.", sourceRecordIds: ["SIM-Q-600"], recordCount: 1, recurrence: "Historical isolated event", severity: "Critical", blockerClassification: "Confirmed blocker", interpretation: "The original route blocked entry, but the corrected path now works.", actionDecision: "Fix Now", recommendedAction: "Retain replacement-link handling and monitor recurrence.", priority: "High", owner: "Hub administrator", targetTiming: "2026-08-12", status: "Verified Closed", verification: "A new learner activation, sign-in and course entry passed on independent retest.", responseArea: "Hub improvement", findingType: "Technical defect", decisionHorizon: "During internal pilot", history: [{ at: "2026-08-12T13:00:00Z", event: "Verified closed after independent retest" }] },
  { id: "SIM-F-002", course: "hrba", domain: "Learning Experience", evidence: "Two smartphone observations and two Final Reviews show the next action can fall below excess whitespace.", sourceRecordIds: ["SIM-Q-601", "SIM-Q-602", "SIM-R-HRBA-01", "SIM-R-HRBA-03"], recordCount: 4, recurrence: "Repeated across two reviewers and two source types", severity: "High", blockerClassification: "Not a blocker", interpretation: "Learners can proceed, but navigation is fragile on smaller screens.", actionDecision: "Improve Before Wider Use", recommendedAction: "Reduce vertical whitespace and retest the next-action position at common phone widths.", priority: "High", owner: "Course production team", targetTiming: "2026-08-25", status: "In Progress", verification: "", responseArea: "Course improvement", findingType: "Usability", decisionHorizon: "Before selected-CSO pilot", history: [{ at: "2026-08-18T10:00:00Z", event: "Repeated pattern promoted to action" }] },
  { id: "SIM-F-003", course: "pm", domain: "Learning & Better Decisions", evidence: "The required risk activity remained locked on retry; assessment and certificate could not be reached.", sourceRecordIds: ["SIM-Q-604", "SIM-Q-605", "SIM-R-PM-04"], recordCount: 3, recurrence: "Repeated attempt plus Final Review confirmation", severity: "Critical", blockerClassification: "Confirmed blocker", interpretation: "This is a critical learner-journey failure; positive ratings elsewhere cannot offset it.", actionDecision: "Fix Now", recommendedAction: "Correct answer mapping, improve diagnostic feedback, and independently retest through certificate.", priority: "High", owner: "Course developer", targetTiming: "2026-08-22", status: "In Progress", verification: "Awaiting corrected build and independent retest.", responseArea: "Course improvement", findingType: "Progression defect", decisionHorizon: "During internal pilot", history: [{ at: "2026-08-14T16:00:00Z", event: "Confirmed blocker and assigned correction" }] },
  { id: "SIM-F-004", course: "hrba", domain: "Learning & Better Decisions", evidence: "Reviewers consistently valued corrective feedback that explains weak role and power decisions.", sourceRecordIds: ["SIM-Q-603", "SIM-R-HRBA-02", "SIM-R-HRBA-06"], recordCount: 3, recurrence: "Positive pattern across three records", severity: "Low", blockerClassification: "Not a blocker", interpretation: "The feedback pattern supports better judgment and should be protected during revisions.", actionDecision: "Retain as Designed", recommendedAction: "Use the same explanatory feedback pattern in future HRBA activities.", priority: "Low", owner: "Learning design lead", targetTiming: "2026-09-15", status: "Action Agreed", verification: "", responseArea: "Course improvement", findingType: "KEEP", decisionHorizon: "Retain / no change", history: [{ at: "2026-08-19T09:00:00Z", event: "Retain decision recorded" }] },
  { id: "SIM-F-005", course: "pm", domain: "Context & Relevance", evidence: "Risk, issue and change terminology is realistic but too compressed for some reviewers.", sourceRecordIds: ["SIM-Q-609", "SIM-R-PM-06"], recordCount: 2, recurrence: "Two linked records", severity: "Medium", blockerClassification: "Not a blocker", interpretation: "The activity works, but a compact distinction would reduce avoidable rereading.", actionDecision: "Improve Before Wider Use", recommendedAction: "Add a short risk/issue/change comparison before the activity.", priority: "Medium", owner: "PM subject lead", targetTiming: "2026-09-05", status: "Action Agreed", verification: "", responseArea: "Course improvement", findingType: "Content clarity", decisionHorizon: "Before wider release", history: [{ at: "2026-08-20T10:00:00Z", event: "Proportionate improvement agreed" }] },
  { id: "SIM-F-006", course: "hub", domain: "DEC Operational Readiness", evidence: "Two phone reviewers found the certificate action less visible than the completion state.", sourceRecordIds: ["SIM-Q-606", "SIM-Q-607", "SIM-R-PM-03", "SIM-R-PM-07"], recordCount: 4, recurrence: "Repeated on smartphone", severity: "High", blockerClassification: "Not a blocker", interpretation: "Completion records work, but the last learner action is fragile on small screens.", actionDecision: "Improve Before Wider Use", recommendedAction: "Strengthen certificate prominence and retest the completed-course panel on phones.", priority: "High", owner: "Hub product team", targetTiming: "2026-08-28", status: "In Progress", verification: "", responseArea: "Hub improvement", findingType: "Usability", decisionHorizon: "Before selected-CSO pilot", history: [{ at: "2026-08-20T14:00:00Z", event: "Mobile completion action assigned" }] },
  { id: "SIM-F-007", course: "hub", domain: "DEC Operational Readiness", evidence: "Support is reachable, but two course reviews suggest placing it nearer the first difficult activity.", sourceRecordIds: ["SIM-Q-608", "SIM-R-HRBA-05", "SIM-R-PM-05"], recordCount: 3, recurrence: "Cross-course support pattern", severity: "Medium", blockerClassification: "Not a blocker", interpretation: "Contextual support would reduce friction without adding a new support channel.", actionDecision: "Improve Before Wider Use", recommendedAction: "Repeat the existing support route beside the first complex activity.", priority: "Medium", owner: "Pilot support lead", targetTiming: "2026-09-02", status: "Under Review", verification: "", responseArea: "Support/process improvement", findingType: "Support need", decisionHorizon: "Validate during selected-CSO pilot", history: [{ at: "2026-08-21T08:00:00Z", event: "Cross-course support evidence grouped" }] },
  { id: "SIM-F-008", course: "hrba", domain: "Access & Entry", evidence: "One interrupted session briefly showed progress one step behind before refresh restored it.", sourceRecordIds: ["SIM-Q-610", "SIM-R-HRBA-08"], recordCount: 2, recurrence: "Single reviewer, two linked records", severity: "High", blockerClassification: "Needs triage", interpretation: "The effect was temporary; recurrence and cause are not yet established.", actionDecision: "Investigate Further", recommendedAction: "Repeat the reconnect test under controlled interrupted connectivity before classification.", priority: "High", owner: "Hub technical lead", targetTiming: "2026-08-27", status: "Under Review", verification: "", responseArea: "Hub improvement", findingType: "Possible blocker", decisionHorizon: "During internal pilot", history: [{ at: "2026-08-18T11:00:00Z", event: "Possible blocker retained for triage, not auto-confirmed" }] },
];
